# SPDX-License-Identifier: Apache-2.0
DEVICE_PATH := device/meizu/m2391

include build/make/target/board/BoardConfigMainlineCommon.mk

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_BOARD_PLATFORM := kalama
TARGET_BOOTLOADER_BOARD_NAME := kalama
TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := false
TARGET_SCREEN_WIDTH := 1440
TARGET_SCREEN_HEIGHT := 3200

